//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass RobotModel
	/// The root in which all other elements are embedded. Appears as a diagram.
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.RobotModel.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.RobotModel.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("55fa0139-cb00-4fa4-863f-f478a6c79aff")]
	public partial class RobotModel : Compound
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// RobotModel domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x55fa0139, 0xcb00, 0x4fa4, 0x86, 0x3f, 0xf4, 0x78, 0xa6, 0xc7, 0x9a, 0xff);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public RobotModel(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public RobotModel(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Hostname domain property code
		
		/// <summary>
		/// Hostname domain property Id.
		/// </summary>
		public static readonly global::System.Guid HostnameDomainPropertyId = new global::System.Guid(0xdc04153d, 0xaef6, 0x4fd1, 0x98, 0x23, 0xde, 0x33, 0x25, 0xe5, 0x64, 0x45);
		
		/// <summary>
		/// Storage for Hostname
		/// </summary>
		private global::System.String hostnamePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Hostname domain property.
		/// Description for SPbSU.RobotsLanguage.RobotModel.Hostname
		/// </summary>
		[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.RobotModel/Hostname.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.RobotModel/Hostname.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("dc04153d-aef6-4fd1-9823-de3325e56445")]
		public global::System.String Hostname
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return hostnamePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				HostnamePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the RobotModel.Hostname domain property.
		/// </summary>
		internal sealed partial class HostnamePropertyHandler : DslModeling::DomainPropertyValueHandler<RobotModel, global::System.String>
		{
			private HostnamePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the RobotModel.Hostname domain property value handler.
			/// </summary>
			public static readonly HostnamePropertyHandler Instance = new HostnamePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the RobotModel.Hostname domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return HostnameDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(RobotModel element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.hostnamePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(RobotModel element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.hostnamePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass AbstractNode
	/// Elements embedded in the model. Appear as boxes on the diagram.
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.AbstractNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.AbstractNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[global::System.Diagnostics.DebuggerDisplay("{GetType().Name,nq} (ElemName = {elemNamePropertyStorage})")]
	[DslModeling::DomainObjectId("55b183c1-cce3-4840-b116-fd5ffad02289")]
	public abstract partial class AbstractNode : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// AbstractNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x55b183c1, 0xcce3, 0x4840, 0xb1, 0x16, 0xfd, 0x5f, 0xfa, 0xd0, 0x22, 0x89);
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		protected AbstractNode(DslModeling::Partition partition, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region ElemName domain property code
		
		/// <summary>
		/// ElemName domain property Id.
		/// </summary>
		public static readonly global::System.Guid ElemNameDomainPropertyId = new global::System.Guid(0x18a7f25c, 0x95fa, 0x4431, 0x99, 0xf4, 0x2c, 0x20, 0xd6, 0xb1, 0xca, 0x3b);
		
		/// <summary>
		/// Storage for ElemName
		/// </summary>
		private global::System.String elemNamePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of ElemName domain property.
		/// Description for SPbSU.RobotsLanguage.AbstractNode.Elem Name
		/// </summary>
		[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.AbstractNode/ElemName.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.AbstractNode/ElemName.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue("")]
		[DslModeling::ElementName]
		[DslModeling::DomainObjectId("18a7f25c-95fa-4431-99f4-2c20d6b1ca3b")]
		public global::System.String ElemName
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return elemNamePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				ElemNamePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the AbstractNode.ElemName domain property.
		/// </summary>
		internal sealed partial class ElemNamePropertyHandler : DslModeling::DomainPropertyValueHandler<AbstractNode, global::System.String>
		{
			private ElemNamePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the AbstractNode.ElemName domain property value handler.
			/// </summary>
			public static readonly ElemNamePropertyHandler Instance = new ElemNamePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the AbstractNode.ElemName domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return ElemNameDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(AbstractNode element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.elemNamePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(AbstractNode element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.elemNamePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region TargetAbstractNode opposite domain role accessor
		
		/// <summary>
		/// Gets a list of TargetAbstractNode.
		/// Description for
		/// SPbSU.RobotsLanguage.AbstractNodeReferencesTargetAbstractNode.SourceAbstractNode
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<AbstractNode> TargetAbstractNode
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<AbstractNode>, AbstractNode>(global::SPbSU.RobotsLanguage.AbstractNodeReferencesTargetAbstractNode.SourceAbstractNodeDomainRoleId);
			}
		}
		#endregion
		#region SourceAbstractNode opposite domain role accessor
		
		/// <summary>
		/// Gets a list of SourceAbstractNode.
		/// Description for
		/// SPbSU.RobotsLanguage.AbstractNodeReferencesTargetAbstractNode.TargetAbstractNode
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<AbstractNode> SourceAbstractNode
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<AbstractNode>, AbstractNode>(global::SPbSU.RobotsLanguage.AbstractNodeReferencesTargetAbstractNode.TargetAbstractNodeDomainRoleId);
			}
		}
		#endregion
		#region Compound opposite domain role accessor
		/// <summary>
		/// Gets or sets Compound.
		/// Description for SPbSU.RobotsLanguage.CompoundHasAbstractNode.AbstractNode
		/// </summary>
		public virtual Compound Compound
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::SPbSU.RobotsLanguage.CompoundHasAbstractNode.AbstractNodeDomainRoleId) as Compound;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::SPbSU.RobotsLanguage.CompoundHasAbstractNode.AbstractNodeDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass StartNode
	/// Description for SPbSU.RobotsLanguage.StartNode
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.StartNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.StartNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("027205a2-e68c-4d40-ba39-ece4a495a665")]
	public partial class StartNode : AbstractNode
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// StartNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x027205a2, 0xe68c, 0x4d40, 0xba, 0x39, 0xec, 0xe4, 0xa4, 0x95, 0xa6, 0x65);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public StartNode(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public StartNode(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass FinishNode
	/// Description for SPbSU.RobotsLanguage.FinishNode
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.FinishNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.FinishNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("dace7fcb-5886-4442-9f1d-26c791759043")]
	public partial class FinishNode : AbstractNode
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// FinishNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xdace7fcb, 0x5886, 0x4442, 0x9f, 0x1d, 0x26, 0xc7, 0x91, 0x75, 0x90, 0x43);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public FinishNode(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public FinishNode(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass Compound
	/// Description for SPbSU.RobotsLanguage.Compound
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.Compound.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.Compound.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("46b80a85-0307-40a7-9260-5fb54debfe60")]
	public abstract partial class Compound : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Compound domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x46b80a85, 0x0307, 0x40a7, 0x92, 0x60, 0x5f, 0xb5, 0x4d, 0xeb, 0xfe, 0x60);
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		protected Compound(DslModeling::Partition partition, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region AbstractNode opposite domain role accessor
		
		/// <summary>
		/// Gets a list of AbstractNode.
		/// Description for SPbSU.RobotsLanguage.CompoundHasAbstractNode.Compound
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<AbstractNode> AbstractNode
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<AbstractNode>, AbstractNode>(global::SPbSU.RobotsLanguage.CompoundHasAbstractNode.CompoundDomainRoleId);
			}
		}
		#endregion
		#region SubprogramNode opposite domain role accessor
		
		/// <summary>
		/// Gets a list of SubprogramNode.
		/// Description for SPbSU.RobotsLanguage.CompoundHasSubprogramNode.Compound
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<SubprogramNode> SubprogramNode
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<SubprogramNode>, SubprogramNode>(global::SPbSU.RobotsLanguage.CompoundHasSubprogramNode.CompoundDomainRoleId);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::SPbSU.RobotsLanguage.SubprogramNode.DomainClassId)) 
				{
					return true;
				}
				
				if (rootElementDomainInfo.IsDerivedFrom(global::SPbSU.RobotsLanguage.AbstractNode.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::SPbSU.RobotsLanguage.SubprogramNode sourceSubprogramNode1 = sourceElement as global::SPbSU.RobotsLanguage.SubprogramNode;
			if (sourceSubprogramNode1 != null)
			{
				// Create link for path CompoundHasSubprogramNode.SubprogramNode
				this.SubprogramNode.Add(sourceSubprogramNode1);

				return;
			}
				
			global::SPbSU.RobotsLanguage.AbstractNode sourceAbstractNode2 = sourceElement as global::SPbSU.RobotsLanguage.AbstractNode;
			if (sourceAbstractNode2 != null)
			{
				// Create link for path CompoundHasAbstractNode.AbstractNode
				this.AbstractNode.Add(sourceAbstractNode2);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::SPbSU.RobotsLanguage.SubprogramNode sourceSubprogramNode1 = sourceElement as global::SPbSU.RobotsLanguage.SubprogramNode;
			if (sourceSubprogramNode1 != null)
			{
				// Delete link for path CompoundHasSubprogramNode.SubprogramNode
				
				foreach (DslModeling::ElementLink link in global::SPbSU.RobotsLanguage.CompoundHasSubprogramNode.GetLinks((global::SPbSU.RobotsLanguage.Compound)this, sourceSubprogramNode1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::SPbSU.RobotsLanguage.CompoundHasSubprogramNode.CompoundDomainRoleId, global::SPbSU.RobotsLanguage.CompoundHasSubprogramNode.SubprogramNodeDomainRoleId);
				}

				return;
			}
				
			global::SPbSU.RobotsLanguage.AbstractNode sourceAbstractNode2 = sourceElement as global::SPbSU.RobotsLanguage.AbstractNode;
			if (sourceAbstractNode2 != null)
			{
				// Delete link for path CompoundHasAbstractNode.AbstractNode
				
				foreach (DslModeling::ElementLink link in global::SPbSU.RobotsLanguage.CompoundHasAbstractNode.GetLinks((global::SPbSU.RobotsLanguage.Compound)this, sourceAbstractNode2))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::SPbSU.RobotsLanguage.CompoundHasAbstractNode.CompoundDomainRoleId, global::SPbSU.RobotsLanguage.CompoundHasAbstractNode.AbstractNodeDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass SubprogramNode
	/// Description for SPbSU.RobotsLanguage.SubprogramNode
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.SubprogramNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.SubprogramNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[global::System.Diagnostics.DebuggerDisplay("{GetType().Name,nq} (ElemName = {elemNamePropertyStorage})")]
	[DslModeling::DomainObjectId("1d4b884e-32b1-4612-92c1-b160b2c70f7a")]
	public partial class SubprogramNode : Compound
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// SubprogramNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x1d4b884e, 0x32b1, 0x4612, 0x92, 0xc1, 0xb1, 0x60, 0xb2, 0xc7, 0x0f, 0x7a);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public SubprogramNode(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public SubprogramNode(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region ElemName domain property code
		
		/// <summary>
		/// ElemName domain property Id.
		/// </summary>
		public static readonly global::System.Guid ElemNameDomainPropertyId = new global::System.Guid(0x02655334, 0x74c7, 0x4a29, 0xb6, 0x38, 0xf2, 0xbf, 0xef, 0xf2, 0x7c, 0x34);
		
		/// <summary>
		/// Storage for ElemName
		/// </summary>
		private global::System.String elemNamePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of ElemName domain property.
		/// Description for SPbSU.RobotsLanguage.SubprogramNode.Elem Name
		/// </summary>
		[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.SubprogramNode/ElemName.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.SubprogramNode/ElemName.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslModeling::ElementName]
		[DslModeling::DomainObjectId("02655334-74c7-4a29-b638-f2bfeff27c34")]
		public global::System.String ElemName
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return elemNamePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				ElemNamePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the SubprogramNode.ElemName domain property.
		/// </summary>
		internal sealed partial class ElemNamePropertyHandler : DslModeling::DomainPropertyValueHandler<SubprogramNode, global::System.String>
		{
			private ElemNamePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the SubprogramNode.ElemName domain property value handler.
			/// </summary>
			public static readonly ElemNamePropertyHandler Instance = new ElemNamePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the SubprogramNode.ElemName domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return ElemNameDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(SubprogramNode element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.elemNamePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(SubprogramNode element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.elemNamePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Compound opposite domain role accessor
		/// <summary>
		/// Gets or sets Compound.
		/// Description for SPbSU.RobotsLanguage.CompoundHasSubprogramNode.SubprogramNode
		/// </summary>
		public virtual Compound Compound
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::SPbSU.RobotsLanguage.CompoundHasSubprogramNode.SubprogramNodeDomainRoleId) as Compound;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::SPbSU.RobotsLanguage.CompoundHasSubprogramNode.SubprogramNodeDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass IfNode
	/// Description for SPbSU.RobotsLanguage.IfNode
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.IfNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.IfNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("616b1380-5ce9-4492-90f2-67434d4a6910")]
	public partial class IfNode : AbstractNode
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// IfNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x616b1380, 0x5ce9, 0x4492, 0x90, 0xf2, 0x67, 0x43, 0x4d, 0x4a, 0x69, 0x10);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public IfNode(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public IfNode(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region condition domain property code
		
		/// <summary>
		/// condition domain property Id.
		/// </summary>
		public static readonly global::System.Guid conditionDomainPropertyId = new global::System.Guid(0x18da06d3, 0x9e00, 0x4b3e, 0x95, 0x95, 0x11, 0x96, 0xa2, 0x10, 0x17, 0x37);
		
		/// <summary>
		/// Storage for condition
		/// </summary>
		private global::System.String conditionPropertyStorage = "condition";
		
		/// <summary>
		/// Gets or sets the value of condition domain property.
		/// Description for SPbSU.RobotsLanguage.IfNode.Condition
		/// </summary>
		[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.IfNode/condition.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.IfNode/condition.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue("condition")]
		[DslModeling::DomainObjectId("18da06d3-9e00-4b3e-9595-1196a2101737")]
		public global::System.String condition
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return conditionPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				conditionPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the IfNode.condition domain property.
		/// </summary>
		internal sealed partial class conditionPropertyHandler : DslModeling::DomainPropertyValueHandler<IfNode, global::System.String>
		{
			private conditionPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the IfNode.condition domain property value handler.
			/// </summary>
			public static readonly conditionPropertyHandler Instance = new conditionPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the IfNode.condition domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return conditionDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(IfNode element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.conditionPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(IfNode element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.conditionPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass EndIfNode
	/// Description for SPbSU.RobotsLanguage.EndIfNode
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.EndIfNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.EndIfNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("5e430085-4c92-4e41-a4b9-1e9790d84b7a")]
	public partial class EndIfNode : AbstractNode
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// EndIfNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x5e430085, 0x4c92, 0x4e41, 0xa4, 0xb9, 0x1e, 0x97, 0x90, 0xd8, 0x4b, 0x7a);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public EndIfNode(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public EndIfNode(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass IterationsNode
	/// Description for SPbSU.RobotsLanguage.IterationsNode
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.IterationsNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.IterationsNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("995b91df-a86f-42ba-9348-bd97a4a50306")]
	public partial class IterationsNode : AbstractNode
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// IterationsNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x995b91df, 0xa86f, 0x42ba, 0x93, 0x48, 0xbd, 0x97, 0xa4, 0xa5, 0x03, 0x06);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public IterationsNode(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public IterationsNode(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region number domain property code
		
		/// <summary>
		/// number domain property Id.
		/// </summary>
		public static readonly global::System.Guid numberDomainPropertyId = new global::System.Guid(0xd0f2e232, 0xee5e, 0x4bb5, 0x8b, 0x18, 0xa8, 0x00, 0xc4, 0xdb, 0xdf, 0xc7);
		
		/// <summary>
		/// Storage for number
		/// </summary>
		private global::System.Int32 numberPropertyStorage = 10;
		
		/// <summary>
		/// Gets or sets the value of number domain property.
		/// Description for SPbSU.RobotsLanguage.IterationsNode.Number
		/// </summary>
		[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.IterationsNode/number.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.IterationsNode/number.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue(10)]
		[DslModeling::DomainObjectId("d0f2e232-ee5e-4bb5-8b18-a800c4dbdfc7")]
		public global::System.Int32 number
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return numberPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				numberPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the IterationsNode.number domain property.
		/// </summary>
		internal sealed partial class numberPropertyHandler : DslModeling::DomainPropertyValueHandler<IterationsNode, global::System.Int32>
		{
			private numberPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the IterationsNode.number domain property value handler.
			/// </summary>
			public static readonly numberPropertyHandler Instance = new numberPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the IterationsNode.number domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return numberDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.Int32 GetValue(IterationsNode element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.numberPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(IterationsNode element, global::System.Int32 newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.Int32 oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.numberPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass SubprogramCallNode
	/// Description for SPbSU.RobotsLanguage.SubprogramCallNode
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.SubprogramCallNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.SubprogramCallNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("15eb50e9-dd1f-4e16-b11b-a0d01aef3718")]
	public partial class SubprogramCallNode : AbstractNode
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// SubprogramCallNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x15eb50e9, 0xdd1f, 0x4e16, 0xb1, 0x1b, 0xa0, 0xd0, 0x1a, 0xef, 0x37, 0x18);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public SubprogramCallNode(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public SubprogramCallNode(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Subprogram domain property code
		
		/// <summary>
		/// Subprogram domain property Id.
		/// </summary>
		public static readonly global::System.Guid SubprogramDomainPropertyId = new global::System.Guid(0x931d49bd, 0x0dfd, 0x43c9, 0xa3, 0x6f, 0x76, 0x8f, 0x7a, 0xa2, 0x46, 0x43);
		
		/// <summary>
		/// Storage for Subprogram
		/// </summary>
		private global::System.String subprogramPropertyStorage = "Subprogram";
		
		/// <summary>
		/// Gets or sets the value of Subprogram domain property.
		/// Description for SPbSU.RobotsLanguage.SubprogramCallNode.Subprogram
		/// </summary>
		[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.SubprogramCallNode/Subprogram.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.SubprogramCallNode/Subprogram.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue("Subprogram")]
		[DslModeling::DomainObjectId("931d49bd-0dfd-43c9-a36f-768f7aa24643")]
		public global::System.String Subprogram
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return subprogramPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				SubprogramPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the SubprogramCallNode.Subprogram domain property.
		/// </summary>
		internal sealed partial class SubprogramPropertyHandler : DslModeling::DomainPropertyValueHandler<SubprogramCallNode, global::System.String>
		{
			private SubprogramPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the SubprogramCallNode.Subprogram domain property value handler.
			/// </summary>
			public static readonly SubprogramPropertyHandler Instance = new SubprogramPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the SubprogramCallNode.Subprogram domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return SubprogramDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(SubprogramCallNode element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.subprogramPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(SubprogramCallNode element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.subprogramPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass ParallelNode
	/// Description for SPbSU.RobotsLanguage.ParallelNode
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.ParallelNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.ParallelNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("1f952800-6025-4a3b-a498-407eccae749e")]
	public partial class ParallelNode : AbstractNode
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// ParallelNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x1f952800, 0x6025, 0x4a3b, 0xa4, 0x98, 0x40, 0x7e, 0xcc, 0xae, 0x74, 0x9e);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public ParallelNode(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public ParallelNode(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass EndParallelNode
	/// Description for SPbSU.RobotsLanguage.EndParallelNode
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.EndParallelNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.EndParallelNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("baf348e3-6cdf-4703-88e5-ce14a8111cc0")]
	public partial class EndParallelNode : AbstractNode
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// EndParallelNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xbaf348e3, 0x6cdf, 0x4703, 0x88, 0xe5, 0xce, 0x14, 0xa8, 0x11, 0x1c, 0xc0);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public EndParallelNode(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public EndParallelNode(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass BreakNode
	/// Description for SPbSU.RobotsLanguage.BreakNode
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.BreakNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.BreakNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("1003be0e-277a-41a3-b4c0-8db1f065aa2a")]
	public partial class BreakNode : AbstractNode
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// BreakNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x1003be0e, 0x277a, 0x41a3, 0xb4, 0xc0, 0x8d, 0xb1, 0xf0, 0x65, 0xaa, 0x2a);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public BreakNode(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public BreakNode(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass SwitchNode
	/// Description for SPbSU.RobotsLanguage.SwitchNode
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.SwitchNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.SwitchNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("4a312676-0f5c-4021-9ac5-e94e81834baa")]
	public partial class SwitchNode : AbstractNode
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// SwitchNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x4a312676, 0x0f5c, 0x4021, 0x9a, 0xc5, 0xe9, 0x4e, 0x81, 0x83, 0x4b, 0xaa);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public SwitchNode(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public SwitchNode(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Condition domain property code
		
		/// <summary>
		/// Condition domain property Id.
		/// </summary>
		public static readonly global::System.Guid ConditionDomainPropertyId = new global::System.Guid(0x142607b8, 0x3b41, 0x4f7b, 0xbf, 0x67, 0x62, 0xfe, 0x2b, 0x48, 0xa7, 0x97);
		
		/// <summary>
		/// Storage for Condition
		/// </summary>
		private global::System.String conditionPropertyStorage = "condition";
		
		/// <summary>
		/// Gets or sets the value of Condition domain property.
		/// Description for SPbSU.RobotsLanguage.SwitchNode.Condition
		/// </summary>
		[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.SwitchNode/Condition.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.SwitchNode/Condition.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue("condition")]
		[DslModeling::DomainObjectId("142607b8-3b41-4f7b-bf67-62fe2b48a797")]
		public global::System.String Condition
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return conditionPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				ConditionPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the SwitchNode.Condition domain property.
		/// </summary>
		internal sealed partial class ConditionPropertyHandler : DslModeling::DomainPropertyValueHandler<SwitchNode, global::System.String>
		{
			private ConditionPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the SwitchNode.Condition domain property value handler.
			/// </summary>
			public static readonly ConditionPropertyHandler Instance = new ConditionPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the SwitchNode.Condition domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return ConditionDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(SwitchNode element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.conditionPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(SwitchNode element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.conditionPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass EndSwitchNode
	/// Description for SPbSU.RobotsLanguage.EndSwitchNode
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.EndSwitchNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.EndSwitchNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("37f16d00-0ec3-4b67-889f-d83d9fc1f99d")]
	public partial class EndSwitchNode : AbstractNode
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// EndSwitchNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x37f16d00, 0x0ec3, 0x4b67, 0x88, 0x9f, 0xd8, 0x3d, 0x9f, 0xc1, 0xf9, 0x9d);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public EndSwitchNode(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public EndSwitchNode(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass MotorsNode
	/// Description for SPbSU.RobotsLanguage.MotorsNode
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.MotorsNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.MotorsNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("e393542d-3924-4231-b0e5-b9d616491e0a")]
	public partial class MotorsNode : AbstractNode
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// MotorsNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xe393542d, 0x3924, 0x4231, 0xb0, 0xe5, 0xb9, 0xd6, 0x16, 0x49, 0x1e, 0x0a);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public MotorsNode(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public MotorsNode(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Ports domain property code
		
		/// <summary>
		/// Ports domain property Id.
		/// </summary>
		public static readonly global::System.Guid PortsDomainPropertyId = new global::System.Guid(0xec2e023f, 0x6a23, 0x4654, 0xb9, 0xad, 0x9f, 0x49, 0x78, 0xe8, 0x2f, 0x0e);
		
		/// <summary>
		/// Storage for Ports
		/// </summary>
		private global::System.String portsPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Ports domain property.
		/// Description for SPbSU.RobotsLanguage.MotorsNode.Ports
		/// </summary>
		[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.MotorsNode/Ports.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.MotorsNode/Ports.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("ec2e023f-6a23-4654-b9ad-9f4978e82f0e")]
		public global::System.String Ports
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return portsPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				PortsPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the MotorsNode.Ports domain property.
		/// </summary>
		internal sealed partial class PortsPropertyHandler : DslModeling::DomainPropertyValueHandler<MotorsNode, global::System.String>
		{
			private PortsPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the MotorsNode.Ports domain property value handler.
			/// </summary>
			public static readonly PortsPropertyHandler Instance = new PortsPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the MotorsNode.Ports domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return PortsDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(MotorsNode element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.portsPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(MotorsNode element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.portsPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Power domain property code
		
		/// <summary>
		/// Power domain property Id.
		/// </summary>
		public static readonly global::System.Guid PowerDomainPropertyId = new global::System.Guid(0x4a139faa, 0x70cc, 0x4432, 0xbf, 0x8e, 0x5d, 0x70, 0xd9, 0x56, 0xa6, 0xaf);
		
		/// <summary>
		/// Storage for Power
		/// </summary>
		private global::System.Int32 powerPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of Power domain property.
		/// Description for SPbSU.RobotsLanguage.MotorsNode.Power
		/// </summary>
		[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.MotorsNode/Power.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.MotorsNode/Power.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("4a139faa-70cc-4432-bf8e-5d70d956a6af")]
		public global::System.Int32 Power
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return powerPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				PowerPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the MotorsNode.Power domain property.
		/// </summary>
		internal sealed partial class PowerPropertyHandler : DslModeling::DomainPropertyValueHandler<MotorsNode, global::System.Int32>
		{
			private PowerPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the MotorsNode.Power domain property value handler.
			/// </summary>
			public static readonly PowerPropertyHandler Instance = new PowerPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the MotorsNode.Power domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return PowerDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.Int32 GetValue(MotorsNode element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.powerPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(MotorsNode element, global::System.Int32 newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.Int32 oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.powerPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass WaitSensorNode
	/// Description for SPbSU.RobotsLanguage.WaitSensorNode
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.WaitSensorNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.WaitSensorNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("114b4e1a-03a9-442b-84a4-4705e1939889")]
	public partial class WaitSensorNode : AbstractNode
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// WaitSensorNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x114b4e1a, 0x03a9, 0x442b, 0x84, 0xa4, 0x47, 0x05, 0xe1, 0x93, 0x98, 0x89);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public WaitSensorNode(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public WaitSensorNode(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Distance domain property code
		
		/// <summary>
		/// Distance domain property Id.
		/// </summary>
		public static readonly global::System.Guid DistanceDomainPropertyId = new global::System.Guid(0xc4862dde, 0xe356, 0x4e62, 0x94, 0x49, 0xf6, 0x4e, 0x90, 0x7d, 0x2b, 0x3f);
		
		/// <summary>
		/// Storage for Distance
		/// </summary>
		private global::System.Int32 distancePropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of Distance domain property.
		/// Description for SPbSU.RobotsLanguage.WaitSensorNode.Distance
		/// </summary>
		[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.WaitSensorNode/Distance.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.WaitSensorNode/Distance.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("c4862dde-e356-4e62-9449-f64e907d2b3f")]
		public global::System.Int32 Distance
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return distancePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DistancePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the WaitSensorNode.Distance domain property.
		/// </summary>
		internal sealed partial class DistancePropertyHandler : DslModeling::DomainPropertyValueHandler<WaitSensorNode, global::System.Int32>
		{
			private DistancePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the WaitSensorNode.Distance domain property value handler.
			/// </summary>
			public static readonly DistancePropertyHandler Instance = new DistancePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the WaitSensorNode.Distance domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return DistanceDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.Int32 GetValue(WaitSensorNode element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.distancePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(WaitSensorNode element, global::System.Int32 newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.Int32 oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.distancePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region ReceivedValue domain property code
		
		/// <summary>
		/// ReceivedValue domain property Id.
		/// </summary>
		public static readonly global::System.Guid ReceivedValueDomainPropertyId = new global::System.Guid(0x1498ec74, 0x4d20, 0x486a, 0x90, 0xbf, 0xa4, 0x2b, 0xad, 0xc5, 0xdc, 0xdb);
		
		/// <summary>
		/// Storage for ReceivedValue
		/// </summary>
		private global::System.String receivedValuePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of ReceivedValue domain property.
		/// Description for SPbSU.RobotsLanguage.WaitSensorNode.Received Value
		/// </summary>
		[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.WaitSensorNode/ReceivedValue.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.WaitSensorNode/ReceivedValue.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("1498ec74-4d20-486a-90bf-a42badc5dcdb")]
		public global::System.String ReceivedValue
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return receivedValuePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				ReceivedValuePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the WaitSensorNode.ReceivedValue domain property.
		/// </summary>
		internal sealed partial class ReceivedValuePropertyHandler : DslModeling::DomainPropertyValueHandler<WaitSensorNode, global::System.String>
		{
			private ReceivedValuePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the WaitSensorNode.ReceivedValue domain property value handler.
			/// </summary>
			public static readonly ReceivedValuePropertyHandler Instance = new ReceivedValuePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the WaitSensorNode.ReceivedValue domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return ReceivedValueDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(WaitSensorNode element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.receivedValuePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(WaitSensorNode element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.receivedValuePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Port domain property code
		
		/// <summary>
		/// Port domain property Id.
		/// </summary>
		public static readonly global::System.Guid PortDomainPropertyId = new global::System.Guid(0x8f38b07f, 0x5e20, 0x4ab3, 0x9e, 0x44, 0xb4, 0x1f, 0xa2, 0x77, 0x6d, 0xe1);
		
		/// <summary>
		/// Storage for Port
		/// </summary>
		private global::System.String portPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Port domain property.
		/// Description for SPbSU.RobotsLanguage.WaitSensorNode.Port
		/// </summary>
		[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.WaitSensorNode/Port.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.WaitSensorNode/Port.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("8f38b07f-5e20-4ab3-9e44-b41fa2776de1")]
		public global::System.String Port
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return portPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				PortPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the WaitSensorNode.Port domain property.
		/// </summary>
		internal sealed partial class PortPropertyHandler : DslModeling::DomainPropertyValueHandler<WaitSensorNode, global::System.String>
		{
			private PortPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the WaitSensorNode.Port domain property value handler.
			/// </summary>
			public static readonly PortPropertyHandler Instance = new PortPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the WaitSensorNode.Port domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return PortDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(WaitSensorNode element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.portPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(WaitSensorNode element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.portPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass DelayNode
	/// Description for SPbSU.RobotsLanguage.DelayNode
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.DelayNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.DelayNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("1eb3ed33-120b-4ebb-9ca0-ffb05f0c55ed")]
	public partial class DelayNode : AbstractNode
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// DelayNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x1eb3ed33, 0x120b, 0x4ebb, 0x9c, 0xa0, 0xff, 0xb0, 0x5f, 0x0c, 0x55, 0xed);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public DelayNode(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public DelayNode(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Time domain property code
		
		/// <summary>
		/// Time domain property Id.
		/// </summary>
		public static readonly global::System.Guid TimeDomainPropertyId = new global::System.Guid(0x2b5dc80b, 0x09db, 0x4230, 0xbc, 0xe8, 0xcd, 0x8e, 0x0e, 0xd8, 0x08, 0xba);
		
		/// <summary>
		/// Storage for Time
		/// </summary>
		private global::System.Int32 timePropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of Time domain property.
		/// Description for SPbSU.RobotsLanguage.DelayNode.Time
		/// </summary>
		[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.DelayNode/Time.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.DelayNode/Time.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("2b5dc80b-09db-4230-bce8-cd8e0ed808ba")]
		public global::System.Int32 Time
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return timePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				TimePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the DelayNode.Time domain property.
		/// </summary>
		internal sealed partial class TimePropertyHandler : DslModeling::DomainPropertyValueHandler<DelayNode, global::System.Int32>
		{
			private TimePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the DelayNode.Time domain property value handler.
			/// </summary>
			public static readonly TimePropertyHandler Instance = new TimePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the DelayNode.Time domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return TimeDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.Int32 GetValue(DelayNode element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.timePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(DelayNode element, global::System.Int32 newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.Int32 oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.timePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass WaitTouchNode
	/// Description for SPbSU.RobotsLanguage.WaitTouchNode
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.WaitTouchNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.WaitTouchNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("d431c58e-bd3c-4e41-bb00-50fccdc9a2e9")]
	public partial class WaitTouchNode : AbstractNode
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// WaitTouchNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xd431c58e, 0xbd3c, 0x4e41, 0xbb, 0x00, 0x50, 0xfc, 0xcd, 0xc9, 0xa2, 0xe9);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public WaitTouchNode(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public WaitTouchNode(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Port domain property code
		
		/// <summary>
		/// Port domain property Id.
		/// </summary>
		public static readonly global::System.Guid PortDomainPropertyId = new global::System.Guid(0x9be727e8, 0x1c51, 0x40b0, 0xb5, 0xad, 0xa6, 0x71, 0xd4, 0xb7, 0x47, 0x42);
		
		/// <summary>
		/// Storage for Port
		/// </summary>
		private global::System.String portPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Port domain property.
		/// Description for SPbSU.RobotsLanguage.WaitTouchNode.Port
		/// </summary>
		[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.WaitTouchNode/Port.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.WaitTouchNode/Port.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("9be727e8-1c51-40b0-b5ad-a671d4b74742")]
		public global::System.String Port
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return portPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				PortPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the WaitTouchNode.Port domain property.
		/// </summary>
		internal sealed partial class PortPropertyHandler : DslModeling::DomainPropertyValueHandler<WaitTouchNode, global::System.String>
		{
			private PortPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the WaitTouchNode.Port domain property value handler.
			/// </summary>
			public static readonly PortPropertyHandler Instance = new PortPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the WaitTouchNode.Port domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return PortDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(WaitTouchNode element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.portPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(WaitTouchNode element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.portPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
	}
}
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainClass MotorsOffNode
	/// Description for SPbSU.RobotsLanguage.MotorsOffNode
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.MotorsOffNode.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.MotorsOffNode.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("e2ffbeae-aa4d-4902-bab7-42abda3786ff")]
	public partial class MotorsOffNode : AbstractNode
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// MotorsOffNode domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xe2ffbeae, 0xaa4d, 0x4902, 0xba, 0xb7, 0x42, 0xab, 0xda, 0x37, 0x86, 0xff);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public MotorsOffNode(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public MotorsOffNode(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Ports domain property code
		
		/// <summary>
		/// Ports domain property Id.
		/// </summary>
		public static readonly global::System.Guid PortsDomainPropertyId = new global::System.Guid(0xdc8c2b23, 0xd5fe, 0x4ddd, 0x92, 0x05, 0x3f, 0x2e, 0x8f, 0x53, 0x1d, 0x7a);
		
		/// <summary>
		/// Storage for Ports
		/// </summary>
		private global::System.String portsPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Ports domain property.
		/// Description for SPbSU.RobotsLanguage.MotorsOffNode.Ports
		/// </summary>
		[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.MotorsOffNode/Ports.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.MotorsOffNode/Ports.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("dc8c2b23-d5fe-4ddd-9205-3f2e8f531d7a")]
		public global::System.String Ports
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return portsPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				PortsPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the MotorsOffNode.Ports domain property.
		/// </summary>
		internal sealed partial class PortsPropertyHandler : DslModeling::DomainPropertyValueHandler<MotorsOffNode, global::System.String>
		{
			private PortsPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the MotorsOffNode.Ports domain property value handler.
			/// </summary>
			public static readonly PortsPropertyHandler Instance = new PortsPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the MotorsOffNode.Ports domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return PortsDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(MotorsOffNode element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.portsPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(MotorsOffNode element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.portsPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
	}
}
