//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace SPbSU.RobotsLanguage
{
	/// <summary>
	/// DomainModel RobotsLanguageDomainModel
	/// Description for SPbSU.RobotsLanguage.RobotsLanguage
	/// </summary>
	[DslDesign::DisplayNameResource("SPbSU.RobotsLanguage.RobotsLanguageDomainModel.DisplayName", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("SPbSU.RobotsLanguage.RobotsLanguageDomainModel.Description", typeof(global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel), "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("f5d71ec9-ccb6-496e-810b-185c031a52a4")]
	public partial class RobotsLanguageDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// RobotsLanguageDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0xf5d71ec9, 0xccb6, 0x496e, 0x81, 0x0b, 0x18, 0x5c, 0x03, 0x1a, 0x52, 0xa4);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public RobotsLanguageDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(RobotModel),
				typeof(AbstractNode),
				typeof(StartNode),
				typeof(FinishNode),
				typeof(Compound),
				typeof(SubprogramNode),
				typeof(IfNode),
				typeof(EndIfNode),
				typeof(IterationsNode),
				typeof(EndIterationsNode),
				typeof(SubprogramCallNode),
				typeof(ParallelNode),
				typeof(EndParallelNode),
				typeof(BreakNode),
				typeof(SwitchNode),
				typeof(EndSwitchNode),
				typeof(AbstractNodeReferencesTargetAbstractNode),
				typeof(CompoundHasAbstractNode),
				typeof(CompoundHasSubprogramNode),
				typeof(RobotsLanguageDiagram),
				typeof(ExampleConnector),
				typeof(Start),
				typeof(Finish),
				typeof(Subprogram),
				typeof(If),
				typeof(EndIf),
				typeof(Iterations),
				typeof(EndIterations),
				typeof(SubprogramCall),
				typeof(Parallel),
				typeof(EndParallel),
				typeof(Break),
				typeof(Switch),
				typeof(EndSwitch),
				typeof(global::SPbSU.RobotsLanguage.FixUpDiagram),
				typeof(global::SPbSU.RobotsLanguage.DecoratorPropertyChanged),
				typeof(global::SPbSU.RobotsLanguage.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(AbstractNode), "ElemName", AbstractNode.ElemNameDomainPropertyId, typeof(AbstractNode.ElemNamePropertyHandler)),
				new DomainMemberInfo(typeof(SubprogramNode), "ElemName", SubprogramNode.ElemNameDomainPropertyId, typeof(SubprogramNode.ElemNamePropertyHandler)),
				new DomainMemberInfo(typeof(IfNode), "condition", IfNode.conditionDomainPropertyId, typeof(IfNode.conditionPropertyHandler)),
				new DomainMemberInfo(typeof(IterationsNode), "number", IterationsNode.numberDomainPropertyId, typeof(IterationsNode.numberPropertyHandler)),
				new DomainMemberInfo(typeof(SubprogramCallNode), "Subprogram", SubprogramCallNode.SubprogramDomainPropertyId, typeof(SubprogramCallNode.SubprogramPropertyHandler)),
				new DomainMemberInfo(typeof(SwitchNode), "Condition", SwitchNode.ConditionDomainPropertyId, typeof(SwitchNode.ConditionPropertyHandler)),
				new DomainMemberInfo(typeof(AbstractNodeReferencesTargetAbstractNode), "Condition", AbstractNodeReferencesTargetAbstractNode.ConditionDomainPropertyId, typeof(AbstractNodeReferencesTargetAbstractNode.ConditionPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(AbstractNodeReferencesTargetAbstractNode), "SourceAbstractNode", AbstractNodeReferencesTargetAbstractNode.SourceAbstractNodeDomainRoleId),
				new DomainRolePlayerInfo(typeof(AbstractNodeReferencesTargetAbstractNode), "TargetAbstractNode", AbstractNodeReferencesTargetAbstractNode.TargetAbstractNodeDomainRoleId),
				new DomainRolePlayerInfo(typeof(CompoundHasAbstractNode), "Compound", CompoundHasAbstractNode.CompoundDomainRoleId),
				new DomainRolePlayerInfo(typeof(CompoundHasAbstractNode), "AbstractNode", CompoundHasAbstractNode.AbstractNodeDomainRoleId),
				new DomainRolePlayerInfo(typeof(CompoundHasSubprogramNode), "Compound", CompoundHasSubprogramNode.CompoundDomainRoleId),
				new DomainRolePlayerInfo(typeof(CompoundHasSubprogramNode), "SubprogramNode", CompoundHasSubprogramNode.SubprogramNodeDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(31);
				createElementMap.Add(typeof(RobotModel), 0);
				createElementMap.Add(typeof(StartNode), 1);
				createElementMap.Add(typeof(FinishNode), 2);
				createElementMap.Add(typeof(SubprogramNode), 3);
				createElementMap.Add(typeof(IfNode), 4);
				createElementMap.Add(typeof(EndIfNode), 5);
				createElementMap.Add(typeof(IterationsNode), 6);
				createElementMap.Add(typeof(EndIterationsNode), 7);
				createElementMap.Add(typeof(SubprogramCallNode), 8);
				createElementMap.Add(typeof(ParallelNode), 9);
				createElementMap.Add(typeof(EndParallelNode), 10);
				createElementMap.Add(typeof(BreakNode), 11);
				createElementMap.Add(typeof(SwitchNode), 12);
				createElementMap.Add(typeof(EndSwitchNode), 13);
				createElementMap.Add(typeof(RobotsLanguageDiagram), 14);
				createElementMap.Add(typeof(ExampleConnector), 15);
				createElementMap.Add(typeof(Start), 16);
				createElementMap.Add(typeof(Finish), 17);
				createElementMap.Add(typeof(Subprogram), 18);
				createElementMap.Add(typeof(If), 19);
				createElementMap.Add(typeof(EndIf), 20);
				createElementMap.Add(typeof(Iterations), 21);
				createElementMap.Add(typeof(EndIterations), 22);
				createElementMap.Add(typeof(SubprogramCall), 23);
				createElementMap.Add(typeof(Parallel), 24);
				createElementMap.Add(typeof(EndParallel), 25);
				createElementMap.Add(typeof(Break), 26);
				createElementMap.Add(typeof(Switch), 27);
				createElementMap.Add(typeof(EndSwitch), 28);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new RobotModel(partition, propertyAssignments);
				case 1: return new StartNode(partition, propertyAssignments);
				case 2: return new FinishNode(partition, propertyAssignments);
				case 3: return new SubprogramNode(partition, propertyAssignments);
				case 4: return new IfNode(partition, propertyAssignments);
				case 5: return new EndIfNode(partition, propertyAssignments);
				case 6: return new IterationsNode(partition, propertyAssignments);
				case 7: return new EndIterationsNode(partition, propertyAssignments);
				case 8: return new SubprogramCallNode(partition, propertyAssignments);
				case 9: return new ParallelNode(partition, propertyAssignments);
				case 10: return new EndParallelNode(partition, propertyAssignments);
				case 11: return new BreakNode(partition, propertyAssignments);
				case 12: return new SwitchNode(partition, propertyAssignments);
				case 13: return new EndSwitchNode(partition, propertyAssignments);
				case 14: return new RobotsLanguageDiagram(partition, propertyAssignments);
				case 15: return new ExampleConnector(partition, propertyAssignments);
				case 16: return new Start(partition, propertyAssignments);
				case 17: return new Finish(partition, propertyAssignments);
				case 18: return new Subprogram(partition, propertyAssignments);
				case 19: return new If(partition, propertyAssignments);
				case 20: return new EndIf(partition, propertyAssignments);
				case 21: return new Iterations(partition, propertyAssignments);
				case 22: return new EndIterations(partition, propertyAssignments);
				case 23: return new SubprogramCall(partition, propertyAssignments);
				case 24: return new Parallel(partition, propertyAssignments);
				case 25: return new EndParallel(partition, propertyAssignments);
				case 26: return new Break(partition, propertyAssignments);
				case 27: return new Switch(partition, propertyAssignments);
				case 28: return new EndSwitch(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(3);
				createElementLinkMap.Add(typeof(AbstractNodeReferencesTargetAbstractNode), 0);
				createElementLinkMap.Add(typeof(CompoundHasAbstractNode), 1);
				createElementLinkMap.Add(typeof(CompoundHasSubprogramNode), 2);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::SPbSU.RobotsLanguage.RobotsLanguageDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new AbstractNodeReferencesTargetAbstractNode(partition, roleAssignments, propertyAssignments);
				case 1: return new CompoundHasAbstractNode(partition, roleAssignments, propertyAssignments);
				case 2: return new CompoundHasSubprogramNode(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "SPbSU.RobotsLanguage.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return RobotsLanguageDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (RobotsLanguageDomainModel.resourceManager == null)
				{
					RobotsLanguageDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(RobotsLanguageDomainModel).Assembly);
				}
				return RobotsLanguageDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return RobotsLanguageDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return RobotsLanguageDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (RobotsLanguageDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new RobotsLanguageCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					RobotsLanguageDomainModel.copyClosure = copyFilter;
				}
				return RobotsLanguageDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (RobotsLanguageDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new RobotsLanguageDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					RobotsLanguageDomainModel.removeClosure = removeFilter;
				}
				return RobotsLanguageDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::SPbSU.RobotsLanguage.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::SPbSU.RobotsLanguage.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::SPbSU.RobotsLanguage.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::SPbSU.RobotsLanguage.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::SPbSU.RobotsLanguage.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::SPbSU.RobotsLanguage.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class RobotsLanguageDeleteClosure : RobotsLanguageDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public RobotsLanguageDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class RobotsLanguageDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public RobotsLanguageDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::SPbSU.RobotsLanguage.CompoundHasAbstractNode.AbstractNodeDomainRoleId, true);
			DomainRoles.Add(global::SPbSU.RobotsLanguage.CompoundHasSubprogramNode.SubprogramNodeDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class RobotsLanguageCopyClosure : RobotsLanguageCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public RobotsLanguageCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class RobotsLanguageCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public RobotsLanguageCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}

