//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPbSU.RobotsLanguage
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "rob";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"RobotsLanguage";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"SPbSU";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID RobotsLanguageDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RobotsLanguageCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID RobotsLanguageExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RobotsLanguageCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewRobotsLanguageExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RobotsLanguageCommandSetId), 0x0001);
	
		// Package identifier
		public const string RobotsLanguagePackageId = "9034a183-e637-44b2-b39d-06082cb16378";
		
		// Editor factory identifier
		public const string RobotsLanguageEditorFactoryId = "17de3b6d-2977-4872-8c4c-43af35df5d04";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string RobotsLanguageModelExplorerToolWindowId = "b86010e1-862e-4092-a2da-9ff6486ba203";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace SPbSU.RobotsLanguage
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string RobotsLanguageCommandSetId = "b8f6b27d-db17-45f1-89d1-e741bf33667e";
	}
}